version: '3'

services:
  whatsapp-bot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: whatsapp-bot
    restart: unless-stopped
    ports:
      - "3000:3000"  # Porta para a API REST
    volumes:
      - ./whatsapp-session:/app/whatsapp-session  # Persistência da sessão do WhatsApp
      - ./actions:/app/actions  # Diretório para scripts de ações personalizadas
    environment:
      - NODE_ENV=production
      - PORT=3000
      # Adicione outras variáveis de ambiente conforme necessário
    networks:
      - whatsapp-network

networks:
  whatsapp-network:
    driver: bridge